name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: sunil/jenkins-action@master
      with:
        url: "http://172.20.0.1:8080"
        user: "sunil"
        token: ${{ 1188f6fbe7a7faef2d4c913aa918bfc8a3 }}
        job: "jenkins-github-webhook"
